### ISSUE TITLE
与RefinedNowPlaying插件冲突

### ISSUE THREAD

**Issue by zhuzixuan2019241** [BetterNCM/StyleSnippet#1]
当打开  Material You 主题 进度条位置修改  ，且安装有  RefinedNowPlaying  时，播放详情页进度条会消失
![image](https://user-images.githubusercontent.com/68471692/210224394-b5c9a263-5050-4030-a5be-561747dadded.png)
![image](https://user-images.githubusercontent.com/68471692/210224413-f4d1f954-d540-46e4-8f61-ff7a477032de.png)

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/214490610-823b4131-e5eb-49c7-8dd4-82b1a83504f0.png)
关掉这个
