### ISSUE TITLE
开侧边栏折叠后页面位移

### ISSUE THREAD

**Issue by Oreficus** [BetterNCM/StyleSnippet#12]
![_4AJD1 CDA(9TF 70BBIIBY](https://user-images.githubusercontent.com/118652957/227431585-d4971f2c-f272-47e4-93a9-d1c37fa56fa0.png)

**Comment by github-tang** [comment]
之前一个版本还是好的

**Comment by Oreficus** [comment]
> 之前一个版本还是不错的

今天更新了material you之后就好了
