### ISSUE TITLE
网易云3.0.0 无法设置背景图片为本地图片

### ISSUE THREAD

**Issue by Minokori** [BetterNCM/StyleSnippet#16]
我想通过 `css` 筛选器将播放页面的背景图片设置为本地图片，尝试了绝对路径发现不太行，将图片放在 `C:\betterncm\StyleSnippets` 文件夹下，也就是 `*.less` 的同文件夹下使用相对路径也不行。
相关代码如下：
```css
[class*="Cover"] //匹配播放背景(这里为了偷懒筛选了包含 ”Cover“)的所有元素, 但好像只有播放页面有 ”Cover“
{
    background-image: url('file:///绝对文件路径') !important;   
}

**Comment by MicroCBer** [comment]
这是正常现象，需要使用本地文件请使用http files接口或mount api

**Comment by MicroCBer** [comment]
![image](https://github.com/BetterNCM/StyleSnippet/assets/66859419/87c08a71-8f9d-40cb-b425-3e24d132f10a)

![image](https://github.com/BetterNCM/StyleSnippet/assets/66859419/e8cdbcba-56fc-4852-a5d6-58f1f4abee34)
