### ISSUE TITLE
启动网易云时无法自动加载主题

### ISSUE THREAD

**Issue by yahayao** [BetterNCM/StyleSnippet#19]
启动网易云的时候没有自动加载主题
![image](https://github.com/user-attachments/assets/fe7a7f44-3943-4c97-a28f-2129788d83c3)
![image](https://github.com/user-attachments/assets/e90b4c93-6dee-4459-9582-f08a26cb4bae)
需要对loacl选项进行更新（如添加配置，打开或关闭配置）才能加载主题
![image](https://github.com/user-attachments/assets/42c0915e-76b9-4d7d-8a30-01b422636729)
![image](https://github.com/user-attachments/assets/3171e38b-02b8-4c3d-8d41-deace2beaa4b)
是relive的问题？

**Comment by DtHnAme** [comment]
感觉可能是StyleSnippet的插件网站挂了导致的

**Comment by DtHnAme** [comment]
找到问题了 
![image](https://github.com/user-attachments/assets/3fd1b7a2-d7ac-4be0-87b3-9833d03515d1)
在index文件135行 缺少了externalSnippetList的依赖 导致初始化时不会加载外部主题

**Comment by DtHnAme** [comment]
我fork了本项目 并修复了此问题
https://github.com/DtHnAme/StyleSnippet/releases/tag/0.2.2
在仓库下载放入 betterncm\plugins 替换即可
