### ISSUE TITLE
侧边栏折叠问题

### ISSUE THREAD

**Issue by Siuroe** [BetterNCM/StyleSnippet#2]
打开侧边栏折叠后，上方文字折叠显示如下
![image](https://user-images.githubusercontent.com/106878922/215827424-bf5348eb-3daa-42dd-a18d-a7285dcbce45.png)
版本为0.1.0

**Comment by huankong233** [comment]
而且侧边栏如果替换了图标，不开机折叠功能，也会出现类似这类的功能，图标右侧的文字会自己移动

**Comment by MicroCBer** [comment]
图标替换就是和侧边栏折叠搭配使用的..
