### ISSUE TITLE
[BUG]侧边栏与主界面重叠

### ISSUE THREAD

**Issue by Ling-Zero** [BetterNCM/StyleSnippet#4]
![image](https://user-images.githubusercontent.com/89287049/216767859-c46f59f7-d49e-48c2-ac91-94695ba0f9b8.png)
如图
我装了下面几个插件，不知道哪里冲突
![image](https://user-images.githubusercontent.com/89287049/216767897-d9ac2636-98ce-470a-abc1-2bbd720287ac.png)

**Comment by MicroCBer** [comment]
你选中了“叠加型”的 snippet，这是正常现象

**Comment by Ling-Zero** [comment]
我的（没看仔细

**Comment by Ling-Zero** [comment]
内个进度条位置修改之后我的进度条在哪，没找到

**Comment by MicroCBer** [comment]
> 内个进度条位置修改之后我的进度条在哪，没找到

没装 Material You 为什么要用这个
